---
# Source: application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gilson-java-application
  labels:
    helm.sh/chart: application-0.1.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: gilson-java
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gilson-java-application
  labels:
    helm.sh/chart: application-0.1.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: gilson-java
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: gilson-java
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gilson-java-application
  labels:
    helm.sh/chart: application-0.1.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: gilson-java
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: application
      app.kubernetes.io/instance: gilson-java
  template:
    metadata:
      labels:
        app.kubernetes.io/name: application
        app.kubernetes.io/instance: gilson-java
    spec:
      serviceAccountName: gilson-java-application
      securityContext:
        {}
      containers:
        - name: application
          securityContext:
            {}
          image: "gbraggion/docker-kube-java:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
# Source: application/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gilson-java-application
  labels:
    helm.sh/chart: application-0.1.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: gilson-java
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: gilson-java-application
                port:
                  number: 80
---
# Source: application/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "gilson-java-application-test-connection"
  labels:
    helm.sh/chart: application-0.1.0
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: gilson-java
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['gilson-java-application:80']
  restartPolicy: Never
